### PR TITLE
Update libraries

### PR DESCRIPTION
**Pull request by sh0hei**

### CODE REVIEW

**Comment by sh0hei** [comment]
@ocadaruma Do you know the cause of this binary-compatibility error?

**Comment by ocadaruma** [comment]
Hmm...weird
Let me check

**Comment by ocadaruma** [comment]
@sh0hei takayahilton submitted another PR, so let's close this PR?
https://github.com/opt-tech/chronoscala/pull/76

**Comment by sh0hei** [comment]
fixed by https://github.com/opt-tech/chronoscala/pull/76 already 👍

**Pull request closed without merging**
